[package]
name = "book_study_unit4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
chrono = "0.4.31"
num-traits = "0.2.14"
num-derive = "0.3.3"