[package]
name = "book_study1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
twox-hash = "1.6.3"
ahash = "0.8.3"